import { useEffect, useState } from "react";
import { Button, Card, Chip } from "@heroui/react";
import { Building2, CalendarCheck, Settings2 } from "lucide-react";
import { api, type AttendanceRecord, type AvailableSystem, type DashboardResponse, type MemberGroup, type Person, type Role, type Tenant } from "../../shared/api/client";
import { today } from "../../shared/page-utils";

export function DashboardDetails({ token, role, tenant, dashboard, onNavigate }: { token: string; role: Role; tenant: Tenant | null; dashboard: DashboardResponse | null; onNavigate: (view: string) => void }) {
  const [people, setPeople] = useState<Person[]>([]); const [groups, setGroups] = useState<MemberGroup[]>([]); const [tenants, setTenants] = useState<Tenant[]>([]); const [systems, setSystems] = useState<AvailableSystem[]>([]); const [records, setRecords] = useState<AttendanceRecord[]>([]);
  useEffect(() => { if (role === "super_admin") { Promise.all([api.tenants(token), api.systems(token)]).then(([a, b]) => { setTenants(a.tenants); setSystems(b.systems); }); } else { Promise.all([api.people(token), api.memberGroups(token), api.attendance(token, { fromDate: today(), toDate: today(), audience: "member" })]).then(([a, b, c]) => { setPeople(a.people); setGroups(b.groups); setRecords(c.records); }).catch(() => undefined); } }, [role, token, dashboard]);
  if (role === "super_admin") return <div className="dashboard-live-panels"><Card className="hero-panel"><Card.Header><h2>Recent tenants</h2></Card.Header><Card.Content>{tenants.slice(0, 5).map((item) => <div className="live-row" key={item.id}><div><strong>{item.name}</strong><span>{item.slug}</span></div><Chip variant="soft" color={item.status === "active" ? "success" : "warning"}>{item.status}</Chip></div>)}{!tenants.length ? <span>No tenants created yet.</span> : null}<Button variant="outline" onPress={() => onNavigate("tenants")}><Building2 size={16} />Manage tenants</Button></Card.Content></Card><Card className="hero-panel"><Card.Header><h2>Available systems</h2></Card.Header><Card.Content>{systems.map((item) => <div className="live-row" key={item.code}><div><strong>{item.name}</strong><span>{item.enabledTenantCount ?? 0} enabled tenants</span></div><Chip variant="soft">{item.status}</Chip></div>)}{!systems.length ? <span>No systems available.</span> : null}<Button variant="outline" onPress={() => onNavigate("systems")}><Settings2 size={16} />Manage systems</Button></Card.Content></Card></div>;
  return <div className="dashboard-live-panels"><Card className="hero-panel"><Card.Header><h2>{tenant?.memberPlural ?? "Members"}</h2></Card.Header><Card.Content><div className="summary-list"><div><span>Total users</span><strong>{people.length}</strong></div><div><span>Active</span><strong>{people.filter((person) => person.status === "active").length}</strong></div><div><span>Pending setup</span><strong>{people.filter((person) => person.requiresOnboarding).length}</strong></div><div><span>{tenant?.memberGroupPlural ?? "Groups"}</span><strong>{groups.length}</strong></div></div></Card.Content></Card><Card className="hero-panel"><Card.Header><h2>Today's member attendance</h2></Card.Header><Card.Content>{records.slice(0, 5).map((item) => <div className="live-row" key={item.id}><strong>{item.personName}</strong><Chip variant="soft" color={item.status === "present" ? "success" : "warning"}>{item.status}</Chip></div>)}{!records.length ? <span>No member attendance recorded today.</span> : null}<Button variant="primary" onPress={() => onNavigate("attendance")}><CalendarCheck size={16} />Open attendance</Button></Card.Content></Card></div>;
}
