import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { Button, Calendar, Card, Chip, Input, Modal, Tabs, TextArea } from "@heroui/react";
import { parseDate } from "@internationalized/date";
import { CalendarDays, ChevronDown, ChevronLeft, ChevronRight, Clock3, Edit3, MapPin, Plus, RefreshCw, RotateCcw, Send, X } from "lucide-react";
import {
  api,
  type MemberGroup,
  type MyScheduleAssignment,
  type Person,
  type Role,
  type ScheduleConflict,
  type ScheduleOccurrence,
  type SchedulePlan,
  type ScheduleResourceStatus,
  type ScheduleSessionTemplate,
  type ScheduleSnapshot,
  type ScheduleSlot,
  type ScheduleTaxonomyNode,
  type ScheduleWeekEntry,
  type ScheduleWeekTemplate,
  type Tenant
} from "./api";
import { ConfirmAction, DataTable, LoadingState, Notice, PageHeader, SearchableMultiSelect, SearchableSelect } from "./components";

const weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
const today = () => new Date().toISOString().slice(0, 10);
const messageOf = (error: unknown) => error instanceof Error ? error.message : "Request failed";
const dateValue = (value: string) => value.slice(0, 10);
const addDays = (value: string, days: number) => { const date = new Date(`${value}T12:00:00Z`); date.setUTCDate(date.getUTCDate() + days); return date.toISOString().slice(0, 10); };
const dateInTimezone = (date: Date, timezone: string) => {
  const parts = new Intl.DateTimeFormat("en", { timeZone: timezone, year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(date);
  const value = Object.fromEntries(parts.map((part) => [part.type, part.value]));
  return `${value.year}-${value.month}-${value.day}`;
};
const timeInTimezone = (date: Date, timezone: string) => {
  const parts = new Intl.DateTimeFormat("en", { timeZone: timezone, hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(date);
  const value = Object.fromEntries(parts.map((part) => [part.type, part.value]));
  return `${value.hour}:${value.minute}`;
};
const parseJson = <T,>(value: T | string, fallback: T): T => { if (typeof value !== "string") return value; try { return JSON.parse(value) as T; } catch { return fallback; } };
const scheduleSnapshot = (value: ScheduleOccurrence["sessionSnapshot"] | MyScheduleAssignment["sessionSnapshot"]) => parseJson(value, { id: 0, name: "Session", durationMinutes: null, objective: null, instructions: null, intensity: null, location: null, equipment: null } as ScheduleSnapshot);
const planTargetIds = (value: number[] | string) => parseJson(value, [] as number[]).map(String);

function Field({ label, value, onChange, type = "text", required = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) {
  return <label className="field-stack"><span className="field-label">{label}{required ? " *" : ""}</span><Input type={type} value={value} required={required} onChange={(event) => onChange(event.target.value)} /></label>;
}

function ArchivedActions({ role, status, noun, onRestore, onDelete, onRecover }: { role: Role; status: ScheduleResourceStatus; noun: string; onRestore: () => Promise<void>; onDelete: () => Promise<void>; onRecover: () => Promise<void> }) {
  if (status === "deleted") return role === "tenant_admin" ? <ConfirmAction label="Recover to archive" title={`Recover this deleted ${noun}?`} description="It will return to archived records and can then be restored to active use." icon={<RotateCcw size={15} />} variant="secondary" onConfirm={onRecover} /> : null;
  return <><ConfirmAction label="Restore" title={`Restore this ${noun}?`} description="It will become available for new scheduling work again." icon={<RotateCcw size={15} />} variant="secondary" onConfirm={onRestore} /><ConfirmAction danger label="Delete" title={`Delete this ${noun}?`} description="It will be removed from operational lists but retained internally for historical references." onConfirm={onDelete} /></>;
}

function pathFor(node: ScheduleTaxonomyNode, nodes: ScheduleTaxonomyNode[]) {
  const path = [node.name]; let parentId = node.parentId; const visited = new Set<number>([node.id]);
  while (parentId) { const parent = nodes.find((item) => item.id === parentId); if (!parent || visited.has(parent.id)) break; path.unshift(parent.name); visited.add(parent.id); parentId = parent.parentId; }
  return path.join(" / ");
}

function weekEntries(value: ScheduleWeekTemplate["entries"]) {
  return parseJson(value ?? [], []).filter((entry): entry is ScheduleWeekEntry => Boolean(entry?.weekday));
}

interface SchedulingData {
  nodes: ScheduleTaxonomyNode[];
  slots: ScheduleSlot[];
  sessions: ScheduleSessionTemplate[];
  weeks: ScheduleWeekTemplate[];
  groups: MemberGroup[];
  people: Person[];
}

const emptyData: SchedulingData = { nodes: [], slots: [], sessions: [], weeks: [], groups: [], people: [] };

export function MemberDashboard({ token, tenant, displayName, timezone, schedulingEnabled, onNavigate }: { token: string; tenant: Tenant | null; displayName: string; timezone: string; schedulingEnabled: boolean; onNavigate: () => void }) {
  const [assignments, setAssignments] = useState<MyScheduleAssignment[]>([]);
  const [memberNow, setMemberNow] = useState(() => new Date());
  const [selectedDate, setSelectedDate] = useState(() => parseDate(dateInTimezone(new Date(), timezone)));
  const [loading, setLoading] = useState(schedulingEnabled);
  const [error, setError] = useState("");
  const memberToday = dateInTimezone(memberNow, timezone);
  const rangeEnd = addDays(memberToday, 120);

  useEffect(() => {
    const updateLocalTime = () => setMemberNow(new Date());
    updateLocalTime();
    const timer = window.setInterval(updateLocalTime, 60_000);
    return () => window.clearInterval(timer);
  }, [timezone]);

  useEffect(() => { setSelectedDate(parseDate(memberToday)); }, [memberToday]);

  useEffect(() => {
    if (!schedulingEnabled) { setLoading(false); return; }
    api.mySchedule(token, memberToday, rangeEnd).then((result) => { setAssignments(result.assignments); setError(""); }).catch((loadError) => setError(messageOf(loadError))).finally(() => setLoading(false));
  }, [memberToday, rangeEnd, schedulingEnabled, token]);

  const memberTime = timeInTimezone(memberNow, timezone);
  const upcoming = assignments.filter((item) => {
    const date = dateValue(item.scheduleDate);
    return date > memberToday || (date === memberToday && (!item.slotStartTime || item.slotStartTime >= memberTime));
  }).slice(0, 8);
  const selectedAssignments = assignments.filter((item) => dateValue(item.scheduleDate) === selectedDate.toString());
  const scheduledDates = useMemo(() => new Set(assignments.map((item) => dateValue(item.scheduleDate))), [assignments]);

  function agendaItem(item: MyScheduleAssignment) {
    const snapshot = scheduleSnapshot(item.sessionSnapshot);
    const path = parseJson(item.taxonomyPath, [] as string[]);
    return <Card key={item.id} className="member-agenda-item"><Card.Content><div className="member-agenda-date"><strong>{new Intl.DateTimeFormat(undefined, { timeZone: "UTC", day: "2-digit" }).format(new Date(`${dateValue(item.scheduleDate)}T12:00:00Z`))}</strong><span>{new Intl.DateTimeFormat(undefined, { timeZone: "UTC", month: "short", weekday: "short" }).format(new Date(`${dateValue(item.scheduleDate)}T12:00:00Z`))}</span></div><div className="primary-cell"><strong>{snapshot.name}</strong><span>{path.join(" / ") || item.planName}</span><div className="agenda-meta"><span><Clock3 size={14} />{item.slotName}{snapshot.durationMinutes ? ` · ${snapshot.durationMinutes} min` : ""}</span>{snapshot.location ? <span><MapPin size={14} />{snapshot.location}</span> : null}</div></div>{snapshot.intensity ? <Chip size="sm" variant="soft">{snapshot.intensity}</Chip> : null}</Card.Content></Card>;
  }

  return <div className="member-dashboard page-stack">
    <PageHeader eyebrow={tenant?.name ?? "Member workspace"} title={`Welcome, ${displayName}`} description="Your upcoming sessions and personal schedule." actions={schedulingEnabled ? <Button variant="primary" onPress={onNavigate}><CalendarDays size={16} />Open my schedule</Button> : undefined} />
    {error ? <Notice message={error} tone="danger" /> : null}
    {!schedulingEnabled ? <Card className="state-card"><Card.Content><CalendarDays /><strong>Scheduling is not enabled</strong><span>Your tenant has not enabled member schedules.</span></Card.Content></Card> : loading ? <LoadingState /> : <div className="member-dashboard-grid">
      <Card className="hero-panel member-agenda"><Card.Header><div><span>Next 120 days</span><h2>Upcoming schedule</h2></div><Chip variant="soft" color="accent">{upcoming.length}</Chip></Card.Header><Card.Content>{upcoming.length ? upcoming.map(agendaItem) : <div className="empty-state"><strong>No upcoming sessions</strong><span>Published sessions will appear here.</span></div>}</Card.Content></Card>
      <div className="member-calendar-column"><Card className="hero-panel member-calendar-card"><Card.Header><div><span>Personal calendar</span><h2>Schedule by date</h2></div></Card.Header><Card.Content><Calendar aria-label="Member schedule calendar" value={selectedDate} minValue={parseDate(memberToday)} maxValue={parseDate(rangeEnd)} onChange={setSelectedDate}><Calendar.Header><Calendar.NavButton slot="previous"><ChevronLeft size={16} /></Calendar.NavButton><Calendar.Heading /><Calendar.NavButton slot="next"><ChevronRight size={16} /></Calendar.NavButton></Calendar.Header><Calendar.Grid><Calendar.GridHeader>{(day) => <Calendar.HeaderCell>{day}</Calendar.HeaderCell>}</Calendar.GridHeader><Calendar.GridBody>{(date) => <Calendar.Cell date={date}>{({ formattedDate }) => <>{formattedDate}{scheduledDates.has(date.toString()) ? <Calendar.CellIndicator /> : null}</>}</Calendar.Cell>}</Calendar.GridBody></Calendar.Grid></Calendar></Card.Content></Card><Card className="hero-panel selected-day-agenda"><Card.Header><div><span>{selectedDate.toString()}</span><h2>Selected day</h2></div><Chip variant="soft">{selectedAssignments.length}</Chip></Card.Header><Card.Content>{selectedAssignments.length ? selectedAssignments.map(agendaItem) : <span>No sessions scheduled for this date.</span>}</Card.Content></Card></div>
    </div>}
  </div>;
}

function ScheduleCalendar({ token, member, timezone }: { token: string; member: boolean; timezone: string }) {
  const resolvedTimezone = timezone || "Asia/Colombo";
  const localToday = () => dateInTimezone(new Date(), resolvedTimezone);
  const [anchor, setAnchor] = useState(localToday);
  const [mode, setMode] = useState<"week" | "month">("week");
  const [items, setItems] = useState<Array<ScheduleOccurrence | MyScheduleAssignment>>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const start = mode === "week" ? addDays(anchor, -(new Date(`${anchor}T12:00:00`).getDay() || 7) + 1) : `${anchor.slice(0, 7)}-01`;
  const end = mode === "week" ? addDays(start, 6) : addDays(`${addDays(start, 32).slice(0, 7)}-01`, -1);
  const load = useCallback(async () => { setLoading(true); try { const data = member ? await api.mySchedule(token, start, end) : await api.scheduleCalendar(token, start, end); setItems(member ? (data as { assignments: MyScheduleAssignment[] }).assignments : (data as { occurrences: ScheduleOccurrence[] }).occurrences); setError(""); } catch (err) { setError(messageOf(err)); } finally { setLoading(false); } }, [end, member, start, token]);
  useEffect(() => { void load(); }, [load]);
  const grouped = useMemo(() => Object.entries(items.reduce<Record<string, Array<ScheduleOccurrence | MyScheduleAssignment>>>((result, item) => { const date = dateValue(item.scheduleDate); (result[date] ??= []).push(item); return result; }, {})).sort(([a], [b]) => a.localeCompare(b)), [items]);

  return <div className="page-stack">
    <PageHeader eyebrow={member ? "Personal calendar" : "Scheduling"} title={member ? "My schedule" : "Schedule calendar"} description={member ? "Your published sessions, in your tenant's local timezone." : "Review draft and published sessions across the tenant calendar."} actions={<Button variant="outline" onPress={() => void load()}><RefreshCw size={16} />Refresh</Button>} />
    <Card className="form-card"><Card.Content><div className="calendar-toolbar"><div className="row-actions"><Button variant={mode === "week" ? "primary" : "secondary"} onPress={() => setMode("week")}>Week</Button><Button variant={mode === "month" ? "primary" : "secondary"} onPress={() => setMode("month")}>Month</Button></div><Field label="Date" type="date" value={anchor} onChange={setAnchor} /><Button variant="outline" onPress={() => setAnchor(localToday())}><CalendarDays size={16} />Today</Button></div></Card.Content></Card>
    {error ? <Notice message={error} tone="danger" /> : null}
    {loading ? <LoadingState /> : grouped.length ? <div className="schedule-calendar-grid">{grouped.map(([date, entries]) => <Card key={date} className="schedule-day"><Card.Header><div><span>{new Intl.DateTimeFormat(undefined, { weekday: "long" }).format(new Date(`${date}T12:00:00`))}</span><h3>{new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric" }).format(new Date(`${date}T12:00:00`))}</h3></div><Chip variant="soft">{entries.length}</Chip></Card.Header><Card.Content>{entries.map((item) => {
      const snapshot = scheduleSnapshot(item.sessionSnapshot);
      const path = parseJson(item.taxonomyPath, [] as string[]);
      return <Card key={item.id} className="schedule-session"><Card.Content><div className="primary-cell"><strong>{snapshot.name}</strong><span>{item.slotName}{snapshot.durationMinutes ? ` · ${snapshot.durationMinutes} min` : ""}</span><small>{path.join(" / ")}</small></div><div className="row-actions"><Chip size="sm" color={item.status === "published" || item.status === "active" ? "success" : "warning"} variant="soft">{item.status}</Chip>{snapshot.intensity ? <Chip size="sm" variant="soft">{snapshot.intensity}</Chip> : null}</div>{snapshot.objective ? <p>{snapshot.objective}</p> : null}{snapshot.location ? <small>{snapshot.location}</small> : null}</Card.Content></Card>;
    })}</Card.Content></Card>)}</div> : <Card className="state-card"><Card.Content><CalendarDays /><strong>No sessions in this period</strong><span>{member ? "Published assignments will appear here." : "Create a draft schedule to begin."}</span></Card.Content></Card>}
  </div>;
}

function TaxonomySetup({ token, data, role, reload }: { token: string; data: SchedulingData; role: Role; reload: () => Promise<void> }) {
  const [editing, setEditing] = useState<ScheduleTaxonomyNode | null>(null); const [open, setOpen] = useState(false);
  const roots = data.nodes.filter((node) => node.parentId === null);
  const start = (parentId: number | null = null, node?: ScheduleTaxonomyNode) => { setEditing(node ?? { id: 0, parentId, name: "", description: "", sortOrder: 0, status: "active" }); setOpen(true); };
  async function save() { if (!editing) return; const payload = { parentId: editing.parentId, name: editing.name, description: editing.description, sortOrder: editing.sortOrder, status: editing.status }; if (editing.id) await api.updateScheduleTaxonomy(token, editing.id, payload); else await api.createScheduleTaxonomy(token, payload); setOpen(false); await reload(); }
  function rows(parentId: number | null, depth = 0): ReactNode[] { return data.nodes.filter((node) => node.parentId === parentId).sort((a, b) => a.sortOrder - b.sortOrder || a.name.localeCompare(b.name)).flatMap((node) => [<Card key={node.id} className="tree-row"><Card.Content><div className="tree-label" style={{ paddingInlineStart: depth * 22 }}>{depth ? <ChevronRight size={15} /> : <ChevronDown size={15} />}<div className="primary-cell"><strong>{node.name}</strong><span>{pathFor(node, data.nodes)}</span></div></div><div className="row-actions"><Chip size="sm" color={node.status === "active" ? "success" : node.status === "deleted" ? "danger" : "warning"} variant="soft">{node.status}</Chip>{node.status === "active" ? <><Button size="sm" variant="ghost" onPress={() => start(node.id)}><Plus size={15} />Child</Button><Button size="sm" variant="outline" onPress={() => start(node.parentId, node)}><Edit3 size={15} />Edit</Button><ConfirmAction danger label="Archive" title="Archive this structure node?" description="Historical schedule snapshots will remain unchanged." onConfirm={async () => { await api.archiveScheduleTaxonomy(token, node.id); await reload(); }} /></> : <ArchivedActions role={role} status={node.status} noun="structure node" onRestore={async () => { await api.restoreScheduleTaxonomy(token, node.id); await reload(); }} onDelete={async () => { await api.deleteScheduleTaxonomy(token, node.id); await reload(); }} onRecover={async () => { await api.recoverScheduleTaxonomy(token, node.id); await reload(); }} />}</div></Card.Content></Card>, ...rows(node.id, depth + 1)]); }
  return <div className="page-stack"><div className="section-heading"><div><h3>Schedule structure</h3><p>Create an unlimited-depth taxonomy for your scheduling language.</p></div><Button variant="primary" onPress={() => start()}><Plus size={16} />Add root</Button></div><div className="tree-list">{roots.length ? rows(null) : <Card className="state-card"><Card.Content><strong>No structure yet</strong><span>Add a root such as Training Schedules.</span></Card.Content></Card>}</div>
    <Modal isOpen={open} onOpenChange={setOpen}><Modal.Backdrop><Modal.Container placement="center"><Modal.Dialog><Modal.CloseTrigger /><Modal.Header><Modal.Heading>{editing?.id ? "Edit structure" : "Add structure"}</Modal.Heading></Modal.Header><Modal.Body>{editing ? <div className="form-grid"><Field label="Name" value={editing.name} onChange={(name) => setEditing({ ...editing, name })} required /><SearchableSelect label="Parent" clearable value={String(editing.parentId ?? "")} onChange={(value) => setEditing({ ...editing, parentId: value ? Number(value) : null })} options={data.nodes.filter((node) => node.id !== editing.id && node.status === "active").map((node) => ({ value: String(node.id), label: pathFor(node, data.nodes) }))} /><label className="field-stack"><span className="field-label">Description</span><TextArea value={editing.description ?? ""} onChange={(event) => setEditing({ ...editing, description: event.target.value })} /></label><Field label="Order" type="number" value={String(editing.sortOrder)} onChange={(sortOrder) => setEditing({ ...editing, sortOrder: Number(sortOrder) })} /></div> : null}</Modal.Body><Modal.Footer><Button variant="ghost" onPress={() => setOpen(false)}><X size={16} />Cancel</Button><ConfirmAction label="Save structure" title="Save this structure node?" description="It will become available to session templates." disabled={!editing?.name} onConfirm={save} /></Modal.Footer></Modal.Dialog></Modal.Container></Modal.Backdrop></Modal>
  </div>;
}

function SlotSetup({ token, data, role, reload }: { token: string; data: SchedulingData; role: Role; reload: () => Promise<void> }) {
  const [editing, setEditing] = useState<ScheduleSlot | null>(null);
  const blank = (): ScheduleSlot => ({ id: 0, name: "", startTime: null, endTime: null, sortOrder: data.slots.length * 10 + 10, status: "active" });
  async function save() { if (!editing) return; const payload = { name: editing.name, startTime: editing.startTime, endTime: editing.endTime, sortOrder: editing.sortOrder, status: editing.status }; if (editing.id) await api.updateScheduleSlot(token, editing.id, payload); else await api.createScheduleSlot(token, payload); setEditing(null); await reload(); }
  return <div className="page-stack"><div className="section-heading"><div><h3>Day slots</h3><p>Define the tenant-local session positions used to prevent conflicting assignments.</p></div><Button variant="primary" onPress={() => setEditing(blank())}><Plus size={16} />Add slot</Button></div><DataTable rows={data.slots} rowKey={(row) => row.id} searchText={(row) => `${row.name} ${row.status}`} columns={[{ header: "Slot", render: (row) => <div className="primary-cell"><strong>{row.name}</strong><span>{row.startTime || "No start"}{row.endTime ? ` - ${row.endTime}` : ""}</span></div> }, { header: "Order", render: (row) => row.sortOrder }, { header: "Status", render: (row) => <Chip color={row.status === "active" ? "success" : row.status === "deleted" ? "danger" : "warning"} variant="soft">{row.status}</Chip> }, { header: "Actions", render: (row) => <div className="row-actions">{row.status === "active" ? <><Button size="sm" variant="outline" onPress={() => setEditing(row)}><Edit3 size={15} />Edit</Button><ConfirmAction danger label="Archive" title="Archive this day slot?" description="Historical sessions keep this slot, but it cannot be selected for new schedules." onConfirm={async () => { await api.archiveScheduleSlot(token, row.id); await reload(); }} /></> : <ArchivedActions role={role} status={row.status} noun="day slot" onRestore={async () => { await api.restoreScheduleSlot(token, row.id); await reload(); }} onDelete={async () => { await api.deleteScheduleSlot(token, row.id); await reload(); }} onRecover={async () => { await api.recoverScheduleSlot(token, row.id); await reload(); }} />}</div> }]} />
    <Modal isOpen={Boolean(editing)} onOpenChange={(value) => { if (!value) setEditing(null); }}><Modal.Backdrop><Modal.Container placement="center"><Modal.Dialog><Modal.CloseTrigger /><Modal.Header><Modal.Heading>{editing?.id ? "Edit day slot" : "Add day slot"}</Modal.Heading></Modal.Header><Modal.Body>{editing ? <div className="form-grid"><Field label="Name" value={editing.name} onChange={(name) => setEditing({ ...editing, name })} required /><Field label="Start time" type="time" value={editing.startTime ?? ""} onChange={(startTime) => setEditing({ ...editing, startTime: startTime || null })} /><Field label="End time" type="time" value={editing.endTime ?? ""} onChange={(endTime) => setEditing({ ...editing, endTime: endTime || null })} /><Field label="Order" type="number" value={String(editing.sortOrder)} onChange={(sortOrder) => setEditing({ ...editing, sortOrder: Number(sortOrder) })} /></div> : null}</Modal.Body><Modal.Footer><Button variant="ghost" onPress={() => setEditing(null)}><X size={16} />Cancel</Button><ConfirmAction label="Save slot" title="Save this day slot?" description="The slot will be available in templates and schedules." disabled={!editing?.name} onConfirm={save} /></Modal.Footer></Modal.Dialog></Modal.Container></Modal.Backdrop></Modal>
  </div>;
}

function SessionSetup({ token, data, role, reload }: { token: string; data: SchedulingData; role: Role; reload: () => Promise<void> }) {
  const [editing, setEditing] = useState<ScheduleSessionTemplate | null>(null);
  const blank = (): ScheduleSessionTemplate => ({ id: 0, name: "", taxonomyNodeId: 0, taxonomyName: "", durationMinutes: null, objective: "", instructions: "", intensity: "", location: "", equipment: "", staffNotes: "", ownerName: "", status: "active" });
  async function save() { if (!editing) return; const { id, taxonomyName: _taxonomyName, ownerName: _ownerName, ...payload } = editing; void _taxonomyName; void _ownerName; if (id) await api.updateScheduleSession(token, id, payload); else await api.createScheduleSession(token, payload); setEditing(null); await reload(); }
  return <div className="page-stack"><div className="section-heading"><div><h3>Session templates</h3><p>Reusable session content is snapshotted when a schedule is generated.</p></div><Button variant="primary" onPress={() => setEditing(blank())}><Plus size={16} />Create session</Button></div><DataTable rows={data.sessions} rowKey={(row) => row.id} searchText={(row) => `${row.name} ${row.taxonomyName} ${row.intensity ?? ""} ${row.status}`} columns={[{ header: "Session", render: (row) => <div className="primary-cell"><strong>{row.name}</strong><span>{pathFor(data.nodes.find((node) => node.id === row.taxonomyNodeId) ?? { id: 0, parentId: null, name: row.taxonomyName, description: null, sortOrder: 0, status: "active" }, data.nodes)}</span></div> }, { header: "Duration", render: (row) => row.durationMinutes ? `${row.durationMinutes} min` : "-" }, { header: "Intensity", render: (row) => row.intensity || "-" }, { header: "Status", render: (row) => <Chip color={row.status === "active" ? "success" : row.status === "deleted" ? "danger" : "warning"} variant="soft">{row.status}</Chip> }, { header: "Actions", render: (row) => <div className="row-actions">{row.status === "active" ? <><Button size="sm" variant="outline" onPress={() => setEditing(row)}><Edit3 size={15} />Edit</Button><ConfirmAction danger label="Archive" title="Archive this session template?" description="Generated schedules retain their immutable snapshot." onConfirm={async () => { await api.archiveScheduleSession(token, row.id); await reload(); }} /></> : <ArchivedActions role={role} status={row.status} noun="session template" onRestore={async () => { await api.restoreScheduleSession(token, row.id); await reload(); }} onDelete={async () => { await api.deleteScheduleSession(token, row.id); await reload(); }} onRecover={async () => { await api.recoverScheduleSession(token, row.id); await reload(); }} />}</div> }]} />
    <Modal isOpen={Boolean(editing)} onOpenChange={(value) => { if (!value) setEditing(null); }}><Modal.Backdrop><Modal.Container placement="center"><Modal.Dialog className="schedule-editor-modal"><Modal.CloseTrigger /><Modal.Header><Modal.Heading>{editing?.id ? "Edit session template" : "Create session template"}</Modal.Heading></Modal.Header><Modal.Body>{editing ? <div className="form-grid"><Field label="Name" value={editing.name} onChange={(name) => setEditing({ ...editing, name })} required /><SearchableSelect label="Taxonomy path *" value={String(editing.taxonomyNodeId || "")} onChange={(value) => setEditing({ ...editing, taxonomyNodeId: Number(value) })} options={data.nodes.filter((node) => node.status === "active").map((node) => ({ value: String(node.id), label: pathFor(node, data.nodes) }))} /><Field label="Duration (minutes)" type="number" value={String(editing.durationMinutes ?? "")} onChange={(value) => setEditing({ ...editing, durationMinutes: value ? Number(value) : null })} /><Field label="Intensity" value={editing.intensity ?? ""} onChange={(intensity) => setEditing({ ...editing, intensity })} /><Field label="Location" value={editing.location ?? ""} onChange={(location) => setEditing({ ...editing, location })} /><label className="field-stack"><span className="field-label">Objective</span><TextArea value={editing.objective ?? ""} onChange={(event) => setEditing({ ...editing, objective: event.target.value })} /></label><label className="field-stack"><span className="field-label">Instructions</span><TextArea value={editing.instructions ?? ""} onChange={(event) => setEditing({ ...editing, instructions: event.target.value })} /></label><label className="field-stack"><span className="field-label">Equipment</span><TextArea value={editing.equipment ?? ""} onChange={(event) => setEditing({ ...editing, equipment: event.target.value })} /></label><label className="field-stack"><span className="field-label">Staff notes</span><TextArea value={editing.staffNotes ?? ""} onChange={(event) => setEditing({ ...editing, staffNotes: event.target.value })} /></label></div> : null}</Modal.Body><Modal.Footer><Button variant="ghost" onPress={() => setEditing(null)}><X size={16} />Cancel</Button><ConfirmAction label="Save session" title="Save this session template?" description="It will be available in week templates and schedule creation." disabled={!editing?.name || !editing?.taxonomyNodeId} onConfirm={save} /></Modal.Footer></Modal.Dialog></Modal.Container></Modal.Backdrop></Modal>
  </div>;
}

function WeekSetup({ token, data, role, reload }: { token: string; data: SchedulingData; role: Role; reload: () => Promise<void> }) {
  const [editing, setEditing] = useState<{ id: number; name: string; description: string; entries: ScheduleWeekEntry[] } | null>(null);
  const activeSlots = data.slots.filter((slot) => slot.status === "active");
  function setCell(weekday: number, slotId: number, value: string) { if (!editing) return; const entries = editing.entries.filter((item) => !(item.weekday === weekday && item.slotId === slotId)); if (value) entries.push({ weekday, slotId, sessionTemplateId: Number(value) }); setEditing({ ...editing, entries }); }
  async function save() { if (!editing) return; const payload = { name: editing.name, description: editing.description || null, status: "active" as const, entries: editing.entries }; if (editing.id) await api.updateScheduleWeekTemplate(token, editing.id, payload); else await api.createScheduleWeekTemplate(token, payload); setEditing(null); await reload(); }
  return <div className="page-stack"><div className="section-heading"><div><h3>Week templates</h3><p>Map one reusable session into each day and slot cell.</p></div><Button variant="primary" onPress={() => setEditing({ id: 0, name: "", description: "", entries: [] })}><Plus size={16} />Create week template</Button></div><DataTable rows={data.weeks} rowKey={(row) => row.id} searchText={(row) => `${row.name} ${row.status}`} columns={[{ header: "Template", render: (row) => <div className="primary-cell"><strong>{row.name}</strong><span>{row.description || "No description"}</span></div> }, { header: "Sessions", render: (row) => weekEntries(row.entries).length }, { header: "Status", render: (row) => <Chip color={row.status === "active" ? "success" : row.status === "deleted" ? "danger" : "warning"} variant="soft">{row.status}</Chip> }, { header: "Actions", render: (row) => <div className="row-actions">{row.status === "active" ? <><Button size="sm" variant="outline" onPress={() => setEditing({ id: row.id, name: row.name, description: row.description ?? "", entries: weekEntries(row.entries) })}><Edit3 size={15} />Edit</Button><ConfirmAction danger label="Archive" title="Archive this week template?" description="Existing plans remain unchanged." onConfirm={async () => { await api.archiveScheduleWeekTemplate(token, row.id); await reload(); }} /></> : <ArchivedActions role={role} status={row.status} noun="week template" onRestore={async () => { await api.restoreScheduleWeekTemplate(token, row.id); await reload(); }} onDelete={async () => { await api.deleteScheduleWeekTemplate(token, row.id); await reload(); }} onRecover={async () => { await api.recoverScheduleWeekTemplate(token, row.id); await reload(); }} />}</div> }]} />
    <Modal isOpen={Boolean(editing)} onOpenChange={(value) => { if (!value) setEditing(null); }}><Modal.Backdrop><Modal.Container placement="center"><Modal.Dialog className="week-editor-modal"><Modal.CloseTrigger /><Modal.Header><Modal.Heading>{editing?.id ? "Edit week template" : "Create week template"}</Modal.Heading></Modal.Header><Modal.Body>{editing ? <div className="page-stack"><div className="form-grid"><Field label="Name" value={editing.name} onChange={(name) => setEditing({ ...editing, name })} required /><label className="field-stack"><span className="field-label">Description</span><TextArea value={editing.description} onChange={(event) => setEditing({ ...editing, description: event.target.value })} /></label></div><div className="week-grid"><div className="week-grid-label">Day</div>{activeSlots.map((slot) => <div key={slot.id} className="week-grid-label">{slot.name}</div>)}{weekdays.map((day, index) => <div className="week-grid-row" key={day}><strong>{day}</strong>{activeSlots.map((slot) => <SearchableSelect key={slot.id} clearable value={String(editing.entries.find((item) => item.weekday === index + 1 && item.slotId === slot.id)?.sessionTemplateId ?? "")} onChange={(value) => setCell(index + 1, slot.id, value)} placeholder="No session" options={data.sessions.filter((session) => session.status === "active").map((session) => ({ value: String(session.id), label: session.name, meta: session.intensity ?? undefined }))} />)}</div>)}</div></div> : null}</Modal.Body><Modal.Footer><Button variant="ghost" onPress={() => setEditing(null)}><X size={16} />Cancel</Button><ConfirmAction label="Save week template" title="Save this week template?" description="The grid will be available when creating schedules." disabled={!editing?.name} onConfirm={save} /></Modal.Footer></Modal.Dialog></Modal.Container></Modal.Backdrop></Modal>
  </div>;
}

function ScheduleSetup({ token, data, role, reload }: { token: string; data: SchedulingData; role: Role; reload: () => Promise<void> }) {
  return <div className="page-stack"><PageHeader eyebrow="Scheduling" title="Schedule setup" description="Build the structure and reusable templates used by your team." /><Tabs className="module-tabs"><Tabs.ListContainer><Tabs.List aria-label="Schedule setup"><Tabs.Tab id="structure">Structure<Tabs.Indicator /></Tabs.Tab><Tabs.Tab id="slots">Day slots<Tabs.Indicator /></Tabs.Tab><Tabs.Tab id="sessions">Session templates<Tabs.Indicator /></Tabs.Tab><Tabs.Tab id="weeks">Week templates<Tabs.Indicator /></Tabs.Tab></Tabs.List></Tabs.ListContainer><Tabs.Panel id="structure"><TaxonomySetup token={token} data={data} role={role} reload={reload} /></Tabs.Panel><Tabs.Panel id="slots"><SlotSetup token={token} data={data} role={role} reload={reload} /></Tabs.Panel><Tabs.Panel id="sessions"><SessionSetup token={token} data={data} role={role} reload={reload} /></Tabs.Panel><Tabs.Panel id="weeks"><WeekSetup token={token} data={data} role={role} reload={reload} /></Tabs.Panel></Tabs></div>;
}

function AddSchedule({ token, tenant, data, reload }: { token: string; tenant: Tenant; data: SchedulingData; reload: () => Promise<void> }) {
  const [form, setForm] = useState({ name: "", mode: "week" as "day" | "week" | "range", startDate: today(), endDate: addDays(today(), 6), weekTemplateId: "", entries: [] as ScheduleWeekEntry[], groupIds: [] as string[], memberIds: [] as string[] });
  const [step, setStep] = useState("details"); const [plans, setPlans] = useState<SchedulePlan[]>([]); const [conflicts, setConflicts] = useState<ScheduleConflict[]>([]); const [replaceIds, setReplaceIds] = useState<string[]>([]); const [selectedPlan, setSelectedPlan] = useState<number | null>(null); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const [editingPlan, setEditingPlan] = useState<{ id: number; name: string; mode?: SchedulePlan["mode"]; startDate?: string; endDate?: string; groupIds: string[]; memberIds: string[] } | null>(null);
  const [reviewingDraftId, setReviewingDraftId] = useState<number | null>(null);
  const loadPlans = useCallback(async () => { try { setPlans((await api.schedulePlans(token, addDays(today(), -366), addDays(today(), 366))).plans); } catch (err) { setError(messageOf(err)); } }, [token]);
  useEffect(() => { void loadPlans(); }, [loadPlans]);
  const activeSlots = data.slots.filter((slot) => slot.status === "active");
  function chooseWeek(value: string) { const week = data.weeks.find((item) => item.id === Number(value)); setForm({ ...form, weekTemplateId: value, entries: week ? weekEntries(week.entries) : [] }); }
  function setCell(weekday: number, slotId: number, value: string) { const entries = form.entries.filter((item) => !(item.weekday === weekday && item.slotId === slotId)); if (value) entries.push({ weekday, slotId, sessionTemplateId: Number(value) }); setForm({ ...form, entries }); }
  async function saveDraft() { const result = await api.createSchedulePlan(token, { name: form.name, mode: form.mode, startDate: form.startDate, endDate: form.mode === "day" ? form.startDate : form.endDate, weekTemplateId: form.weekTemplateId ? Number(form.weekTemplateId) : null, entries: form.entries, groupIds: form.groupIds.map(Number), memberIds: form.memberIds.map(Number) }); setSelectedPlan(result.id); setNotice(`Draft created with ${result.occurrenceCount} sessions`); await Promise.all([loadPlans(), reload()]); setStep("publish"); await preview(result.id); }
  async function preview(planId: number) { const result = await api.scheduleConflicts(token, planId); setReviewingDraftId(null); setSelectedPlan(planId); setConflicts(result.conflicts); setReplaceIds([]); setStep("publish"); }
  async function publish() { if (!selectedPlan) return; await api.publishSchedule(token, selectedPlan, replaceIds.map(Number)); setNotice("Schedule published successfully"); setConflicts([]); setSelectedPlan(null); await loadPlans(); }
  async function savePlanEdit() { if (!editingPlan) return; const source = plans.find((plan) => plan.id === editingPlan.id); if (!source) return; const startDate = editingPlan.startDate ?? dateValue(source.startDate); const endDate = source.mode === "day" ? startDate : editingPlan.endDate ?? dateValue(source.endDate); await api.updateSchedulePlan(token, editingPlan.id, { name: editingPlan.name, startDate, endDate, groupIds: editingPlan.groupIds.map(Number), memberIds: editingPlan.memberIds.map(Number) }); setNotice("Draft schedule updated"); const id = editingPlan.id; setEditingPlan(null); await loadPlans(); if (selectedPlan === id) await preview(id); }
  function cancelPublish() { if (!selectedPlan) return; setReviewingDraftId(selectedPlan); setSelectedPlan(null); setConflicts([]); setReplaceIds([]); setStep("review"); }
  async function deleteDraft(planId: number) { await api.deleteSchedulePlan(token, planId); setReviewingDraftId(null); setSelectedPlan(null); setConflicts([]); setNotice("Draft schedule deleted"); await loadPlans(); setStep("publish"); }
  const canContinue = form.name && form.startDate && (form.mode === "day" || form.endDate);
  const reviewingDraft = plans.find((plan) => plan.id === reviewingDraftId) ?? null;
  const editingPlanSource = editingPlan ? plans.find((plan) => plan.id === editingPlan.id) ?? null : null;
  return <div className="page-stack"><PageHeader eyebrow="Scheduling" title="Add schedule" description={`Generate a tenant-local schedule and assign it to ${tenant.memberGroupPlural.toLowerCase()} or individual ${tenant.memberPlural.toLowerCase()}.`} />{notice ? <Notice message={notice} tone="success" /> : null}{error ? <Notice message={error} tone="danger" /> : null}
    <Tabs className="module-tabs" selectedKey={step} onSelectionChange={(key) => setStep(String(key))}><Tabs.ListContainer><Tabs.List aria-label="Schedule creation"><Tabs.Tab id="details">1. Details<Tabs.Indicator /></Tabs.Tab><Tabs.Tab id="grid">2. Session grid<Tabs.Indicator /></Tabs.Tab><Tabs.Tab id="assign">3. Assign<Tabs.Indicator /></Tabs.Tab><Tabs.Tab id="review">4. Review<Tabs.Indicator /></Tabs.Tab><Tabs.Tab id="publish">5. Publish<Tabs.Indicator /></Tabs.Tab></Tabs.List></Tabs.ListContainer>
      <Tabs.Panel id="details"><Card className="form-card"><Card.Content><div className="form-grid"><Field label="Schedule name" value={form.name} onChange={(name) => setForm({ ...form, name })} required /><SearchableSelect label="Schedule period" value={form.mode} onChange={(mode) => { const next = mode as typeof form.mode; setForm({ ...form, mode: next, endDate: next === "day" ? form.startDate : next === "week" ? addDays(form.startDate, 6) : form.endDate }); }} options={[{ value: "day", label: "One day" }, { value: "week", label: "Seven days" }, { value: "range", label: "Date range" }]} /><Field label="Start date" type="date" value={form.startDate} onChange={(startDate) => setForm({ ...form, startDate, endDate: form.mode === "day" ? startDate : form.mode === "week" ? addDays(startDate, 6) : form.endDate })} required />{form.mode !== "day" ? <Field label="End date" type="date" value={form.endDate} onChange={(endDate) => setForm({ ...form, endDate })} required /> : null}<SearchableSelect label="Week template" clearable value={form.weekTemplateId} onChange={chooseWeek} placeholder="Start blank" options={data.weeks.filter((week) => week.status === "active").map((week) => ({ value: String(week.id), label: week.name }))} /></div><div className="form-actions"><Button variant="primary" isDisabled={!canContinue} onPress={() => setStep("grid")}>Continue<ChevronRight size={16} /></Button></div></Card.Content></Card></Tabs.Panel>
      <Tabs.Panel id="grid"><Card className="form-card"><Card.Content><div className="week-grid"><div className="week-grid-label">Day</div>{activeSlots.map((slot) => <div key={slot.id} className="week-grid-label">{slot.name}</div>)}{weekdays.map((day, index) => <div className="week-grid-row" key={day}><strong>{day}</strong>{activeSlots.map((slot) => <SearchableSelect key={slot.id} clearable value={String(form.entries.find((item) => item.weekday === index + 1 && item.slotId === slot.id)?.sessionTemplateId ?? "")} onChange={(value) => setCell(index + 1, slot.id, value)} placeholder="No session" options={data.sessions.filter((session) => session.status === "active").map((session) => ({ value: String(session.id), label: session.name }))} />)}</div>)}</div><div className="form-actions"><Button variant="ghost" onPress={() => setStep("details")}>Back</Button><Button variant="primary" isDisabled={!form.entries.length} onPress={() => setStep("assign")}>Continue<ChevronRight size={16} /></Button></div></Card.Content></Card></Tabs.Panel>
      <Tabs.Panel id="assign"><Card className="form-card"><Card.Content><div className="form-grid"><SearchableMultiSelect label={tenant.memberGroupPlural} values={form.groupIds} onChange={(groupIds) => setForm({ ...form, groupIds })} options={data.groups.filter((group) => group.status === "active").map((group) => ({ value: String(group.id), label: group.name, meta: `${group.memberCount} ${tenant.memberPlural}` }))} /><SearchableMultiSelect label={`Individual ${tenant.memberPlural}`} values={form.memberIds} onChange={(memberIds) => setForm({ ...form, memberIds })} options={data.people.filter((person) => person.role === "tenant_member" && person.status === "active").map((person) => ({ value: String(person.id), label: person.displayName, meta: person.userIdentifier ?? undefined }))} /></div><Notice message="Members selected through multiple classes or directly are automatically deduplicated when publishing." /><div className="form-actions"><Button variant="ghost" onPress={() => setStep("grid")}>Back</Button><Button variant="primary" isDisabled={!form.groupIds.length && !form.memberIds.length} onPress={() => setStep("review")}>Review<ChevronRight size={16} /></Button></div></Card.Content></Card></Tabs.Panel>
      <Tabs.Panel id="review">{reviewingDraft ? <Card className="form-card"><Card.Header><h3>Review draft schedule</h3></Card.Header><Card.Content><div className="summary-list"><div><span>Name</span><strong>{reviewingDraft.name}</strong></div><div><span>Dates</span><strong>{dateValue(reviewingDraft.startDate)} to {dateValue(reviewingDraft.endDate)}</strong></div><div><span>Generated sessions</span><strong>{reviewingDraft.occurrenceCount}</strong></div><div><span>Targets</span><strong>{planTargetIds(reviewingDraft.groupIds).length} {tenant.memberGroupPlural.toLowerCase()}, {planTargetIds(reviewingDraft.memberIds).length} direct</strong></div></div><div className="form-actions"><ConfirmAction danger label="Delete draft" title="Permanently delete this draft?" description="The draft and all of its generated sessions will be removed. This cannot be undone." onConfirm={() => deleteDraft(reviewingDraft.id)} /><Button variant="outline" onPress={() => setEditingPlan({ id: reviewingDraft.id, name: reviewingDraft.name, groupIds: planTargetIds(reviewingDraft.groupIds), memberIds: planTargetIds(reviewingDraft.memberIds) })}><Edit3 size={16} />Edit draft</Button><Button variant="primary" onPress={() => void preview(reviewingDraft.id)}><Send size={16} />Review publish</Button></div></Card.Content></Card> : <Card className="form-card"><Card.Header><h3>Review generated schedule</h3></Card.Header><Card.Content><div className="summary-list"><div><span>Name</span><strong>{form.name}</strong></div><div><span>Dates</span><strong>{form.startDate}{form.mode !== "day" ? ` to ${form.endDate}` : ""}</strong></div><div><span>Template cells</span><strong>{form.entries.length}</strong></div><div><span>Targets</span><strong>{form.groupIds.length} {tenant.memberGroupPlural.toLowerCase()}, {form.memberIds.length} direct</strong></div></div><div className="form-actions"><Button variant="ghost" onPress={() => setStep("assign")}>Back</Button><ConfirmAction label="Save draft" title="Create this draft schedule?" description="Sessions will be snapshotted now. You can review conflicts before publishing." onConfirm={saveDraft} /></div></Card.Content></Card>}</Tabs.Panel>
      <Tabs.Panel id="publish">
        <div className="page-stack">
          {selectedPlan ? <Card className="form-card"><Card.Header><h3>Publish review</h3></Card.Header><Card.Content>{conflicts.length ? <><Notice message={`${conflicts.length} existing assignment${conflicts.length === 1 ? "" : "s"} conflict with this schedule. Select the ones you intend to replace.`} tone="warning" /><SearchableMultiSelect label="Assignments to replace" values={replaceIds} onChange={setReplaceIds} options={conflicts.map((conflict) => ({ value: String(conflict.assignmentId), label: conflict.memberName, meta: `${dateValue(conflict.scheduleDate)} · ${conflict.slotName} · ${conflict.existingSessionName}` }))} /></> : <Notice message="No assignment conflicts were found. This draft is ready to publish." tone="success" />}<div className="form-actions"><Button variant="ghost" onPress={cancelPublish}><X size={16} />Cancel publish</Button><ConfirmAction label="Publish schedule" title="Publish this schedule?" description={conflicts.length ? "Selected existing assignments will become historical and link to their replacements." : "Assigned members will be able to see these sessions immediately."} disabled={conflicts.length > 0 && replaceIds.length !== conflicts.length} icon={<Send size={16} />} onConfirm={publish} /></div></Card.Content></Card> : null}
          <DataTable rows={plans.filter((plan) => plan.status === "draft")} rowKey={(row) => row.id} searchText={(row) => `${row.name} ${row.ownerName}`} empty="No draft schedules." columns={[{ header: "Draft", render: (row) => <div className="primary-cell"><strong>{row.name}</strong><span>{dateValue(row.startDate)} to {dateValue(row.endDate)}</span></div> }, { header: "Sessions", render: (row) => row.occurrenceCount }, { header: "Owner", render: (row) => row.ownerName }, { header: "Actions", render: (row) => <div className="row-actions"><Button size="sm" variant="outline" onPress={() => setEditingPlan({ id: row.id, name: row.name, groupIds: planTargetIds(row.groupIds), memberIds: planTargetIds(row.memberIds) })}><Edit3 size={15} />Edit</Button><Button size="sm" variant="secondary" onPress={() => void preview(row.id)}><Send size={15} />Review publish</Button></div> }]} />
        </div>
      </Tabs.Panel>
    </Tabs>
    <Modal isOpen={Boolean(editingPlan)} onOpenChange={(open) => { if (!open) setEditingPlan(null); }}><Modal.Backdrop isDismissable={false}><Modal.Container placement="center"><Modal.Dialog className="schedule-editor-modal"><Modal.CloseTrigger /><Modal.Header><Modal.Heading>Edit draft schedule</Modal.Heading></Modal.Header><Modal.Body>{editingPlan && editingPlanSource ? <div className="page-stack"><Field label="Schedule name" value={editingPlan.name} onChange={(name) => setEditingPlan({ ...editingPlan, name })} required /><div className="form-grid"><Field label="Start date" type="date" value={editingPlan.startDate ?? dateValue(editingPlanSource.startDate)} onChange={(startDate) => setEditingPlan({ ...editingPlan, startDate, endDate: editingPlanSource.mode === "day" ? startDate : editingPlan.endDate })} required />{editingPlanSource.mode !== "day" ? <Field label="End date" type="date" value={editingPlan.endDate ?? dateValue(editingPlanSource.endDate)} onChange={(endDate) => setEditingPlan({ ...editingPlan, endDate })} required /> : null}</div><SearchableMultiSelect label={tenant.memberGroupPlural} values={editingPlan.groupIds} onChange={(groupIds) => setEditingPlan({ ...editingPlan, groupIds })} options={data.groups.filter((group) => group.status === "active").map((group) => ({ value: String(group.id), label: group.name, meta: `${group.memberCount} ${tenant.memberPlural}` }))} /><SearchableMultiSelect label={`Individual ${tenant.memberPlural}`} values={editingPlan.memberIds} onChange={(memberIds) => setEditingPlan({ ...editingPlan, memberIds })} options={data.people.filter((person) => person.role === "tenant_member" && person.status === "active").map((person) => ({ value: String(person.id), label: person.displayName, meta: person.userIdentifier ?? undefined }))} /><Notice message="Changing dates regenerates the draft calendar while preserving its saved session and taxonomy snapshots." /></div> : null}</Modal.Body><Modal.Footer><Button variant="ghost" onPress={() => setEditingPlan(null)}><X size={16} />Discard</Button><ConfirmAction label="Save changes" title="Save draft changes?" description="Dates, schedule name, and member assignments will be updated before conflict review." disabled={!editingPlan?.name || (!editingPlan.groupIds.length && !editingPlan.memberIds.length)} onConfirm={savePlanEdit} /></Modal.Footer></Modal.Dialog></Modal.Container></Modal.Backdrop></Modal>
  </div>;
}

export function SchedulingPage({ token, tenant, role, timezone, section }: { token: string; tenant: Tenant; role: Role; timezone: string; section: "calendar" | "add" | "setup" | "my" }) {
  const [data, setData] = useState<SchedulingData>(emptyData); const [loading, setLoading] = useState(section !== "calendar" && section !== "my"); const [error, setError] = useState("");
  const load = useCallback(async () => { if (role === "tenant_member") return; setLoading(true); try { const [nodes, slots, sessions, weeks, groups, people] = await Promise.all([api.scheduleTaxonomy(token), api.scheduleSlots(token), api.scheduleSessions(token), api.scheduleWeekTemplates(token), api.memberGroups(token), api.people(token)]); setData({ nodes: nodes.nodes, slots: slots.slots, sessions: sessions.templates, weeks: weeks.templates, groups: groups.groups, people: people.people }); setError(""); } catch (err) { setError(messageOf(err)); } finally { setLoading(false); } }, [role, token]);
  useEffect(() => { void load(); }, [load]);
  if (section === "my") return <ScheduleCalendar token={token} member timezone={timezone} />;
  if (section === "calendar") return <ScheduleCalendar token={token} member={false} timezone={timezone} />;
  if (loading) return <LoadingState />;
  if (error) return <div className="page-stack"><Notice message={error} tone="danger" /><Button variant="outline" onPress={() => void load()}><RefreshCw size={16} />Retry</Button></div>;
  if (section === "setup") return <ScheduleSetup token={token} data={data} role={role} reload={load} />;
  return <AddSchedule token={token} tenant={tenant} data={data} reload={load} />;
}
