import { useEffect, useState } from "react";
import { Card } from "@heroui/react";
import { api, type AuthUser, type Tenant } from "../../shared/api/client";
import { ConfirmAction, Notice, PageHeader, SearchableSelect } from "../../shared/components";
import { Field } from "../../shared/components/Field";
import { messageOf, timezoneOptions } from "../../shared/page-utils";

export function ProfilePage({ session, tenant, onSession }: { session: { token: string; user: AuthUser }; tenant: Tenant | null; onSession: (session: { token: string; user: AuthUser }) => void }) {
  const [profile, setProfile] = useState({ ...session.user, timezone: session.user.timezone || "Asia/Colombo" }); const [passwords, setPasswords] = useState({ currentPassword: "", newPassword: "" }); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  useEffect(() => { api.profile(session.token).then((data) => setProfile(data.user)).catch((err) => setError(messageOf(err))); }, [session.token]);
  return <div className="page-stack"><PageHeader eyebrow="Account" title="Profile and security" description="Manage your identity and login credentials." />{notice ? <Notice message={notice} tone="success" /> : null}{error ? <Notice message={error} tone="danger" /> : null}<div className="split-panels"><Card className="form-card"><Card.Header><h3>Profile</h3></Card.Header><Card.Content><Field label="Display name" value={profile.displayName} onChange={(displayName) => setProfile({ ...profile, displayName })} /><Field label="Email" type="email" value={profile.email ?? ""} onChange={(email) => setProfile({ ...profile, email })} />{tenant ? <><Field label={tenant.userIdentifierLabel} value={profile.userIdentifier ?? ""} onChange={(userIdentifier) => setProfile({ ...profile, userIdentifier })} /><Field label={tenant.newUserIdentifierLabel} value={profile.newUserIdentifier ?? ""} onChange={(newUserIdentifier) => setProfile({ ...profile, newUserIdentifier })} /></> : null}<SearchableSelect label="Timezone" value={profile.timezone} onChange={(timezone) => setProfile({ ...profile, timezone })} options={timezoneOptions} /><ConfirmAction label="Save profile" title="Save profile changes?" description="Your session and displayed local time will update immediately." onConfirm={async () => { const next = await api.updateProfile(session.token, { displayName: profile.displayName, email: profile.email, userIdentifier: profile.userIdentifier, newUserIdentifier: profile.newUserIdentifier, timezone: profile.timezone }); onSession(next); setProfile(next.user); setNotice("Profile updated"); }} /></Card.Content></Card><Card className="form-card"><Card.Header><h3>Password</h3></Card.Header><Card.Content><Field label="Current password" type="password" value={passwords.currentPassword} onChange={(currentPassword) => setPasswords({ ...passwords, currentPassword })} /><Field label="New password" type="password" value={passwords.newPassword} onChange={(newPassword) => setPasswords({ ...passwords, newPassword })} /><ConfirmAction label="Change password" title="Change your password?" description="Use the new password the next time you sign in." disabled={!passwords.currentPassword || passwords.newPassword.length < 8} onConfirm={async () => { await api.updatePassword(session.token, passwords); setPasswords({ currentPassword: "", newPassword: "" }); setNotice("Password changed"); }} /></Card.Content></Card></div></div>;
}
